name: "Setup"
description: "Setup environment"

runs:
  using: composite
  steps:
    # setup
    - uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

    # install dependencies
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
    - run: bun install --frozen-lockfile
      shell: bash
